### ISSUE TITLE
kernel: boot issues and graphics issues with AMD Ryzen 5/7

### ISSUE THREAD

**Issue by Galaxy1496** [linuxmint/mint20.1-beta#43] opened 2020-12-22 03:40 UTC
Thank you Clem for addressing my question about LM compatibility with AMD Ryzen/Radeon hardware. There is a blog about it located at: https://forums.linuxmint.com/viewtopic.php?f=49&t=326612&p=1857931&hilit=radeon+vega+drivers#p1857931

Number 1 thing to consider (important) LM on AMD hardware will not boot with the 5.4 kernel… won’t happen, you need to go with 5.8 or higher. I will post my log of a recent successful boot at the referenced github site. You will see that I am running the latest 10.1 kernel and that seems to work pretty well with my hardware (Stock Dell LT with Ryzen7, Radeon Vega GPU.

When it Boots!
[log messages21122020.txt](https://github.com/linuxmint/mint20.1-beta/files/5727667/log.messages21122020.txt)

**Comment by OdinVex** [comment] 2020-12-22 04:25
I seem to recall that being a Mesa issue being the cause but fixing it also required a 5.5+ kernel. I could be wrong on the version. I'd recommend following this up with https://github.com/linuxmint/mint20.1-beta/issues/33.

**Comment by Galaxy1496** [comment] 2020-12-22 06:26
Thanks OV but that is not a permanent fix for this issue...
See:  LiquidIce32December 17, 2020 at 7:24 pm
https://blog.linuxmint.com/?p=3989

"Does 20.1 come with an updated graphics stack? I’ve finally tracked down a bug that causes Mint 20.0 to freeze, and it’s somewhere in the AMD graphics stack. Updating from the oibaf PPA doesn’t fix the issue, but installing AMDGPU-PRO seems to fix it.
Unfortunately, AMDGPU-PRO fails to install correctly and causes a number of side effects because that’s just how AMDGPU-PRO rolls."

The Oibaf Mesa drivers will boot about 50% of the time and the boot sequence freezes on the other 50%. You have to fool the AMD GPU drivers to make it appear that you're running Ubuntu instead of LM.  I have never been able to get the AMD linux drivers to install properly...  LI32's post above pretty much sums up the situation.

**Comment by OdinVex** [comment] 2020-12-22 06:42
I experienced freezing too when game developing but it was mostly limited to a memory leak in Vulkan. I ran Oibaf as well. I only ran pro's CL and optionals without core because the amdgpu-pro driver is 'eh' compared to amdgpu. I never experienced your level of instability though...I did skip a few versions of Mesa from Oibaf because of serious bugs (the versions were even pulled from release because of it). You don't need "AMD Linux Drivers". You only need amdgpu for GPU and if you want OpenCL, amdgpu-pro opencl ONLY. Throw Vulkan on-top. You'll have no problem with Vulkan games and you can use hwaccel with Blender, etc but celluloid, mpv, and steam hardware acceleration will fail. Pretty much why I left Mint for EndeavourOS+Manjaro. No longer held back. Again, amdgpu-pro is pretty much crap and yields lower performance, only install OpenCL from it if you need it, otherwise do not use it.

*Edit* Also left Mint because of the Ubuntu underside. I despise the Gnome CSD.

**Comment by Galaxy1496** [comment] 2020-12-22 06:48
When LM boots on the AMD hardware it works very well... I have measured 8K+ fps of accelerated graphics.  No limitations noted in any of the native apps.

**Comment by OdinVex** [comment] 2020-12-22 07:09
Benchmarks without context are completely useless.

It has become common knowledge that Mesa had issues with Kernel 5.4 and under in a way that affected AMD hardware. Any 5.5+ will be fine and there are a few 5.4s that were okay. Recommend closing thread.

**Comment by Galaxy1496** [comment] 2020-12-22 07:27
You have provided arrogant nonsense... not answers. Sorry

**Comment by OdinVex** [comment] 2020-12-22 07:39
You clearly can't comprehend anything. Not sorry. Good luck, though.

**Comment by SimonIremonger** [comment] 2020-12-22 12:10
I wonder if there should be a process like that used by MXLinux, they have an "AHS" iso with updated kernel and other tools (even without all such being LTS) and I would suspect in the immedate-term it may be rational for Clem to consider something similar -- Mastering 20.1-ahs isos' that include k5.8 (and possibly other updated packages) out of the box.  In all cases the alternate-X-stack / drivers  should also be installable via mintdrivers / mintupdate options.
I like the idea of debian, ubuntu, mint starting to offer multi-kernel-option (at least) bootable images, in general, but, where appropriate, providing "alternate" boot images may be a good pragmatic first solution meeting many peoples' combined needs initially.

**Comment by Galaxy1496** [comment] 2020-12-22 12:31
Thank you Simon...

**Comment by Galaxy1496** [comment] 2020-12-23 11:46
Here is a link to the Dell AMD LT... https://www.dell.com/en-us/shop/dell-laptops/new-inspiron-15-3000-laptop/spd/inspiron-15-3505-laptop/nn3505ejwyh  The Problem is:  Linux Mint 20 and most likely 20.1 will not boot reliably on computers running AMD Ryzen/Radeon chipsets.  Changing to a different kernel does not fix this.  Installing the Oibaf Mesa drivers does not fix this...

See: LiquidIce32December 17, 2020 at 7:24 pm
https://blog.linuxmint.com/?p=3989 

Clem wrote: https://blog.linuxmint.com/?p=3989#comment-172281

**Comment by Acheron17** [comment] 2020-12-26 13:35
If I could just chime in a bit on this subject.  There is a huge problem right now in Linux with the RX Vega 10 Graphics drivers.  Some hardware suppliers who build Linux systems have suspended using them in 'Linux ready' configurations.  System76 is one of them.

**Comment by Galaxy1496** [comment] 2020-12-26 16:14
Thank you Harry...  Let's hope the developers will devote some time to this problem.

**Comment by SimonIremonger** [comment] 2020-12-30 12:58
@Galaxy1496   I'm not sure I've seen failed boot-log, videos, etc ....   #ubuntu-kernel  people are quite willing to look into but they (and mint) need clear detailed information, in short.
Given other general bugs with 5.4.0-58 kernel (touchpad, usb, wifi ....), I'm wondering how many issue symptomatic of kernel issues, personally I'd consider lm 20.1 should either provide an earlier e.g. -54 kernel or the next 'fixed' ubuntu version when it comes-out, so that don't create needless issues for those booting/installing.

**Comment by Galaxy1496** [comment] 2020-12-30 16:38
I would guess that if your system freezes on boot then there would be no log which contains a record of what did not happen...

That is one of the problems with the Linux Grub implementation:  They need to create a step by step feature so that you can advance the boot one line at a time in order to see what is happening so one can troubleshoot issues like this.  If this feature exists then I have never heard about it.

**Comment by clefebvre** [comment] 2020-12-30 17:47
@SimonIremonger it's really hit and miss though... I mean -56 was a disaster.. -54 has fixed bugs and also touchpad not detected issues... regressions happen all the time, we'd almost need a second BETA if we were to pick another one.

**Comment by clefebvre** [comment] 2020-12-30 17:48
What I'd like to know is this: Without upgrading/installing anything else, just by switching to a 5.8 kernel, can you boot the AMD Ryzen 5 with Mint 20?

**Comment by SimonIremonger** [comment] 2020-12-30 21:04
I note, Ubuntu Kernel team about to produce a new kernel.  -59 is apparently to start going to 'testing' [maybe focal-proposed] tomorrow!.  Changelog here suggests lots of USB and AMDGPU fixes, small mention of new AMD CPUs, amongst a lot else:-
https://paste.ubuntu.com/p/vdw94dvHTy/
Timescale suggests new kernel release ver to be out in a week:-
https://kernel.ubuntu.com/
If theres' many many changes to mint20.1 I do think a second-beta with 5.4.0-59 or 5.4.0-60 (along with instructions for debug info collection on unbootable machines... -- with specific appeal for this testing and clear beta2 feedback path!) might not be a bad idea, at all.  Personally I wouldn't hurry matters in this time of lockdown and difficulty for all.
Given incompatibilites with some kernel-module builds not compatible with k5.8 I don't reccomend that mint 20.1 is *only* supplied with 5.8 kernel.  I *like* the idea of a HWE/AHS type install image being produced later (maybe when Ryzen situation clearer), but the 20.1 really ought to be better debugged in my opinion.

**Comment by Galaxy1496** [comment] 2020-12-31 01:23
Clem asked: "What I'd like to know is this: Without upgrading/installing anything else, just by switching to a 5.8 kernel, can you boot the AMD Ryzen 5 with Mint 20?"  I have a Ryzen 7 system, here are the details...  The machine boots into LM20 about one out of 5 tries.  When it boots it works very well, the graphics performance is outstanding.

I have kernel 5.8.14 installed and I will try to boot with it the next time I turn on the machine.

![Screenshot from 2020-12-31 09-15-15](https://user-images.githubusercontent.com/38918569/103389410-91751f80-4b49-11eb-92ce-ee4c84798133.png)

**Comment by SimonIremonger** [comment] 2021-01-01 01:11
@Galaxy1496   OK look like you have an ubuntu-supplied upstream 5.10.4 kernel manually added.

Would be particularly helpful to know how current mint-supplied 5.4 and 5.8 kernels behave on the system.   mintupdate has a menu for linux-kernels and should offer to install latest 'released' 5.4 and 5.8 kernels provided by ubuntu+mint.  You can usually get the GRUB menu to appear by holding down shift key when the bios/uefi is about to boot the system.  Does the 'one out of five' behavior apply to all kernels?

Ideally, for booting any kernel that boots intermittently, be useful to take out the "quiet splash" from the kernel commandline (e.g. by editing manually at grub menu) so the kernel and system messages are visible, and taking a photo of the screen when the boot has jammed/failed.

**Comment by Galaxy1496** [comment] 2021-01-01 04:25
Hello Simon,
Here are the variations of the kernels you mentioned that are installed on my Dell, AMD laptop. I can tell you with some degree of assurance that the 5.4 version will not work at all.  The 5.8.14 will boot occasionally but I observed some instability in the system when it would be left on for long periods. I have been trying these other kernels and the 5.10.4 version exhibits great stability... When I can get it to boot.  I can leave the computer on for days, suspending the system when I'm not working and it remains very stable.  Some of the earlier kernels would work but the machine would freeze when you tried to wake it up from the suspended mode...

![Screenshot from 2021-01-01 12-07-04](https://user-images.githubusercontent.com/38918569/103433371-f8b6d080-4c2a-11eb-85ca-31043d34c005.png)
![Screenshot from 2021-01-01 12-07-54](https://user-images.githubusercontent.com/38918569/103433379-0c623700-4c2b-11eb-990f-280d393091ac.png)

**Comment by SimonIremonger** [comment] 2021-01-01 22:32
@clefebvre  Further investigation shows the following :-
1) Seems that ubuntu are about to use 5.8.0-34-generic as the  linux-generic-hwe   (i.e. not just hwe-edge any more), the metapackage for this is already in focal-proposed.
2) (5.4.0-59-generic  kernel similary to be released in about 3 days [ 4th Jan. ])
3) updated linux-firmware in focal-proposed similarly to release
4) ubuntu are also about to update all the mesa drivers in focal too -- va/vdpau/vulkan to 20.2.6 versions, Bear in mind these are not separate -hwe  versions so will hit all ubuntu20.04/mint20 users soon  unless sufficient ubuntu bug-reports stop this.
5) ubuntu also about to release new xserver-xorg-core xserver-xorg-legacy xserver-common  (maybe more minor change).
6) asking about in more technical communities confirms updated drivers/kernel seem to be important for new AMD ryzen's, this is known issue, seemingly.  I still would like clear bug-reports to be given to the Ubuntu-Kernel team in any case, they may at least improve 5.4 somewhat.

I would propose, that rest of important Beta bugs are corrected, and a new Beta image is produced in a week that incorporates the released ubuntu updates especially kernel 5.4.0-59-generic and firmware.
I would propose the ether the default boot entry on Beta Live USB is modifed to remove "quiet splash" on kernel commandline [or an extra entry in both legacy+UEFI boot menus is provided, with same effect].  In this way, those testing the beta-image can more easily photograph what the last boot messages actually are!.  BETA2 can, in my view, happily default to showing kernel/system messages openly.

In any case, I think its' highly likely a second image with linux-generic-hwe-20.04 (kernel 5.8.0-34!) and xserver-xorg-hwe-20.04 will be wanted in any case (either provided around the same process delayed), but the imminent ubuntu updates may improve matters and will, in any case start hitting mint and ubuntu users more generally.  I defintely want to see LTS 5.4 kernel image always an option in all cases.   Ideally, ultimately, both images will merge and become "boot menu choices" on same image, at the very least 2 kernel choices available.

**Comment by SimonIremonger** [comment] 2021-01-01 22:54
OK looks like the xorg/mesa are mostly to be sorted in time for 20.04.2 release by next month, might be longer to release than the kernel/firmware packages, as per:-
https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1902244

**Comment by Galaxy1496** [comment] 2021-01-02 03:13
Some good news for the New Year!  Thanks for the report...

I have been trying catch a picture of the error message on the boot screen when the boot sequence freezes but it has not been as easy as one would think.  I'll keep working on it...

It is only about 3-4 lines but goes by so fast I cannot read all of it. When the machine does boot the Dell logo flashes for a fraction of a second and then the lines from the error message appear and then if this same sequence repeats a second time, the machine will boot into the LM OS.  If this sequence shows only once, the boot freezes.

**Comment by clefebvre** [comment] 2021-01-02 13:32
I think we'll go ahead with this release as is but rather than have an extra "stable" ISO with kernel 5.8, we might go for a testing ISO we can re-generate and re-update multiple times on the 20.04 base. This would give us more flexibility and we wouldn't be tied to the 6 months release cycle. It could also potentially free our hands in the future and let us stick to LTS without jumping towards HWE... it's way too soon to think about this, but for now I think it's pretty clear we need to provide a 5.8 ISO, and it sounds better to not associate it strictly with the stable release.

It's also much simpler and much safer than shipping with multiple kernels on the same ISO. It greatly reduces testing cases and impacts on live and installation components.

We'll definitely have a 5.8 ISO, we just need to think about the strategy and nomenclature.

**Comment by Galaxy1496** [comment] 2021-01-02 15:21
Merci Beaucoup, Clem.
Happy New Year!

**Comment by clefebvre** [comment] 2021-01-02 18:51
Thank you, Happy New Year :)

**Comment by clefebvre** [comment] 2021-01-03 12:20
I'll close this here. We'll release an ISO with a kernel 5.8.

**Closed as completed by clefebvre** 2021-01-03 12:20 UTC

**Comment by SimonIremonger** [comment] 2021-01-03 20:46
FWIW, Ubuntu 20.04.2 will release desktop iso with HWE kernel 5.8 as I understand it.  They are scheduled for Feb 11th release.
