### ISSUE TITLE
Ubiquity : keyboard is modified during LM installation

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20.1-beta#3] opened 2020-12-16 15:51 UTC
LM 20 and 20.1 Cinnamon. Install choosing French language and keyboard "Français (azerty)" or "Français".
At the screen asking to choose a computer and a user names, the keyboard is still QWERTY instead of AZERTY (q instead of a...).
![95636441-74233e80-0a8f-11eb-8f15-e05eb8ded6f6](https://user-images.githubusercontent.com/3955499/102371809-df711b80-3fbe-11eb-88a0-c0e8070ed9c3.png)

https://github.com/linuxmint/linuxmint/issues/311

**Comment by clefebvre** [comment] 2020-12-29 13:46
I'll close this issue here since I can't reproduce it but I'll leave the original one open.

**Comment by clefebvre** [comment] 2020-12-29 17:50
Fixed.

**Closed as completed by clefebvre** 2020-12-29 17:50 UTC
