### ISSUE TITLE
webapp-manager: New apps need a new login to appear

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20.1-beta#30] opened 2020-12-20 12:48 UTC
Dear Mint Team, 

Linux Mint 20.1 Cinnamon: So far a newly created webappp needs a new login to appear in the menu. It would be great if this does not require a new login.

**Comment by MenthaSuaveolens** [comment] 2020-12-21 15:26
I can confirm the issue.

1. Create new user
2. Log in
3. Create webapp => no new entries in menu
4. Logout
5. Login => all entries are created

**Comment by MenthaSuaveolens** [comment] 2020-12-21 15:57
It is more subtle. Once you have created a webapp and logged out and in again. Then all new webapp appear at once into the menu. After this sequence, the software seems to behave proper. All new ones show up at once into the menu

Test (After the sequence mentioned)
1. Delete all Web Apps => all entries are removed from the menu
2. Create a new one => entry shows up immediately
3. Change type of entry => entry is moved into the right place

**Comment by clefebvre** [comment] 2020-12-21 16:16
Xfce looks fine.. It doesn't work in MATE and it doesn't work in Cinnamon.

I think it might have to do with ~/.local/share/applications not existing when the DE starts, which results in no monitoring taking place on that directory.

**Comment by clefebvre** [comment] 2020-12-21 16:17
Fixed in mint-artwork 1.4.8.

**Closed as completed by clefebvre** 2020-12-21 16:17 UTC

**Comment by crhy** [comment] 2021-01-01 03:28
Can confirm.  Working now.  Great job team!
