### ISSUE TITLE
Glitches that sometimes occur when Mint's chromium browser is running or minimized

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20.1-beta#16] opened 2020-12-18 19:12 UTC
```
 * muffin version: 4.8.0
 * Distribution - Linux Mint 20.1 Cinnamon Beta
 * Graphics hardware: Intel HD Graphics 5500
 * Graphics Driver: i915
 * Display Driver: modesetting
 * Architecture: 64 bit
 ```

**Issue**
The chromium browser sometimes fails to restore by clicking its icon on the panel after being minimized by clicking the minimize button on the title bar. When attempting to restore the browser after minimizing, the desktop icons are not clickable and the browser's icon on the panel is in an active state. At least once when the browser does not restore well, a horizontal full line (white colour iirc) appears on the screen for a few moments. Also at least once when using the browser for a while maybe at least an hour, many short horizontal flickering lines (black in colour iirc on the default classic theme) appear on the browser's active window for a few moments.

**Steps to reproduce**
1. Install the chromium package in Linux Mint 20.1 Cinnamon beta from the mint repository.
2. Launch the browser and navigate to Settings -> Appearance.
3. Disable the 'use system title bar and borders' option.
4. Change the theme to the classic theme.
5. Use the browser for a while with at least 3 tabs open and minimize it by clicking the minimize button on the title bar and restore it.

**Expected behaviour**
The chromium browser should restore well after it has been minimized without any glitches and no lines should appear sometimes when the browser is being used.

**Comment by clefebvre** [comment] 2020-12-18 21:09
Can you paste the output of `inxi -Gxx`?

**Comment by clefebvre** [comment] 2020-12-18 21:12
I can't reproduce it here:

```
Graphics:  Device-1: Intel Iris Pro Graphics 6200 driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:1622 
Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
resolution: 2560x1440~60Hz, 2560x1440~60Hz 
OpenGL: renderer: Mesa Intel Iris Pro Graphics 6200 (BDW GT3) v: 4.6 Mesa 20.0.8 direct render: Yes
```

**Comment by ghost** [comment] 2020-12-19 07:09
Output of `inxi -Gxx`:
```
Graphics:  Device-1: Intel HD Graphics 5500 vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:1616 
Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.0.8 direct render: Yes
```

Rasterization is hardware accelerated on all pages by default in Mint's chromium package and in both Google Chrome and Brave browser rasterization is software only by default. The 'use hardware acceleration when available' option is on by default in all the three browsers.

Below is a screenshot of Graphics feature status of both Brave Browser and Google chrome by default:
![image](https://user-images.githubusercontent.com/64726924/102691321-a635e700-421c-11eb-9c4d-eacebc8281ca.png)

Below is a screenshot of Graphics feature status of Mint's chromium package:
![image](https://user-images.githubusercontent.com/64726924/102691347-d5e4ef00-421c-11eb-9ce1-485b05462504.png)

I disabled GPU Rasterization for chromium via about:flags (experimental flags) and restarted the browser. The browser behaved as expected. The browser restores well every time it has been minimized and no glitches have occurred with this change.

**Comment by BertBoer1** [comment] 2021-01-01 15:38
This behaviour reminds me of Chromium and Google Chrome on Linux Mint 18.1 on my notebook with i5-4210U Intel® HD Graphics 4400.
It happened after an update of above mentioned applications around halfway 2020. The description as mentioned in the first post of maximizing from minimize where the desktop icons are not clickable is because the redraw of Chromium or Chrome is not completed, so in fact the desktop is now taken by the window of Chromium or Chrome, but the contents of that window is not redrawn.
Solution: Go into Settings->Advanced->System and switch "Use hardware acceleration when available" to OFF.
Looks like a Chromium and Google Chrome bug.

**Comment by clefebvre** [comment] 2021-01-01 21:08
I agree, I would have liked to reproduce it but I don't think it's something we can fix on our side. I'll close this since it won't block the release.

**Closed as completed by clefebvre** 2021-01-01 21:08 UTC
