### ISSUE TITLE
Cinnamon menu: Moving icons in Favorites vertical bar doesn't work very well

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20.1-beta#5] opened 2020-12-16 16:20 UTC
LM 20.1.

When I move an icon in the Favorites vertical bar (drag and drop), it doesn't work very well. When I drop the icon, it doesn't always move where I place it.

![96366854-9a5d7400-114a-11eb-9b0c-10be198d0040](https://user-images.githubusercontent.com/3955499/102375586-fc0f5280-3fc2-11eb-831b-6fef0c2b0d20.png)

https://github.com/linuxmint/cinnamon/issues/9654

**Comment by clefebvre** [comment] 2020-12-18 16:49
Closing as it's now new and I can't reproduce it. I'm leaving it open in Cinnamon's repo for other team members to see if they can.

**Closed as completed by clefebvre** 2020-12-18 16:49 UTC
