### ISSUE TITLE
Touchpad does not register at edges.

### ISSUE THREAD

**Issue by BertBoer1** [linuxmint/mint20.1-beta#38] opened 2020-12-21 09:40 UTC
Comparing with Mint Cinnamon 18.3 and now running Mint Cinnamon 20.1 Beta Live.
My laptop has an edge and 2 finger capable scrolling touchpad.
I noticed that in Cinnamon 20.1 the mouse pointer is 'numb' when touching the touchpad on the edges, about 7 mm into the touchpad from the edge. When I move my finger from the 7mm edge inside the touchpad to the centre the mouse pointer on the screen does not move at all, it is 'numb'. That goes for the left, right and bottom of the touchpad. However moving my finger from the TOP 7mm edge of the touchpad the mouse pointer moves like normal.
Touching inside the 7mm edge boundary in the centre of the touchpad the mouse pointer works normal from edge to edge also into the 7mm border.
I noticed similar behaviour in Mate 20.1
I also noticed that in Mint 18.3 you could use both 2 finger and edge scrolling together, however in Mint 20.1 it is either/or. Hopefully the more extensive settings in Mint 18.3 can be brought back into Mint 20.1. However it is of a lesser concern.

Hardware:
$ lshw  
bert-acer
    description: Notebook
    product: TMP645-M (TMP645-M_081E_V2.14)
    vendor: Acer
    version: V2.14
    serial: NXV8RED00243806EB33400
    width: 64 bits
    capabilities: smbios-2.7 dmi-2.7 vsyscall32
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 2641MHz
          capacity: 2700MHz
          width: 64 bits
          clock: 100MHz

$ cat /proc/bus/input/devices
I: Bus=0011 Vendor=0002 Product=0007 Version=01b1
N: Name="SynPS/2 Synaptics TouchPad"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input6
U: Uniq=
H: Handlers=mouse0 event6 
B: PROP=1
B: EV=b
B: KEY=e520 30000 0 0 0 0
B: ABS=660800011000003

**Comment by clefebvre** [comment] 2020-12-30 12:54
There are many touchpad related issues with kernel 5.4.0-58. Can you try to reproduce this with Mint 20 (i.e. 20.0)?

**Comment by BertBoer1** [comment] 2020-12-30 17:33
I am downloading Ubuntu 20.04 and Mint 20 right now. In the mean time I experimented with Mint 19.3.
I tried Mint 19.3 in live mode with defaults and the problem with the 'numb' mouse pointer also occurs in the 7 mm edge on the left and right side of the touchpad, but top and bottom works like normal.

I happened to read the release notes of Mint 19.3 and it says in Known Issues:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
The default touchpad driver in this edition is "libinput" (provided by the xserver-xorg-input-libinput-hwe-18.04 package).

If you experience problems with it, you can switch to another driver called "synaptics" (provided by the xserver-xorg-input-synaptics-hwe-18.04 package).

To know which driver is used by your input devices, run the following command:

grep -i "Using input driver" /var/log/Xorg.0.log
When both drivers are installed, "synaptics" takes priority.

To switch to the "synaptics" driver, install it with the command:

apt install xserver-xorg-input-synaptics-hwe-18.04
Then log out and log back in.

To go back to using "libinput", simply remove the "synaptics" driver:

apt remove xserver-xorg-input-synaptics-hwe-18.04
Then log out and log back in.

Note: You can also try installing the "evdev" driver (provided by the xserver-xorg-input-evdev-hwe-18.04).
-----------------------------------------------------------------------------------------------------------------------------------------------------------
I installed the synaptics driver as xserver-xorg-input-synaptics-hwe-18.04 but package could not be found. Then I tried xserver-xorg-input-synaptics and that could be installed. But the keyboard didn't work anymore after logout/login.
I tried xserver-xorg-input-evdev but then the mouse didn't work but keyboard did after logout/login.
Anyhow a delicate business, so I will let you know how I get on with Ubuntu 20.1 and Mint 20 later on.

**Comment by BertBoer1** [comment] 2020-12-30 21:11
I tested with several installations. It looks like this bug only happens on the LHS and RHS of the touchpad where the 7 mm edge is 'numb' (see description earlier). This happens with Ubuntu 18.04 and higher and derivatives like Mint 19 and higher. 
If I compare Mint 18.1 (derivative of Ubuntu 16.04) and all later like 19.3 (derivative of Ubuntu 18.04), 20, 20.1 Beta and Ubuntu 20.04.1 Looks like the new driver libinput is the cause of this issue. And this started in Mint 19 (Ubuntu 18.04). This issue was discovered earlier looking at the release notes "Known issues": Touchpad drivers. Reason I never saw that before is because I just now am looking for the latest update since I am running Mint 18.1 Cinnamon which is coming close to EOL.
So I could reproduce in Ubuntu therefore it is not a Mint error, but rather Ubuntu. Only thing I can do is to post this bug to Ubuntu and ask Mint to keep this issue in "Known issues": Touchpad Drivers, in the release notes for Mint 20.1 (as is now in Mint 20). Maybe this bug has to do with older hardware (my laptop is gen 4 Intel, so about 7 years old I guess).
Linux Mint 18.1 Cinnamon
$ sudo grep -i "Using input driver" /var/log/Xorg.0.log
[sudo] password for bert: 
[    13.798] (II) Using input driver 'evdev' for 'Power Button'
[    13.814] (II) Using input driver 'evdev' for 'Video Bus'
[    13.815] (II) Using input driver 'evdev' for 'Power Button'
[    13.816] (II) Using input driver 'evdev' for 'Sleep Button'
[    13.818] (II) Using input driver 'evdev' for 'HD WebCam'
[    13.820] (II) Using input driver 'evdev' for 'AT Translated Set 2 keyboard'
[    13.821] (II) Using input driver 'synaptics' for 'SynPS/2 Synaptics TouchPad'
[    13.920] (II) Using input driver 'evdev' for 'Acer WMI hotkeys'


Linux Mint 19.3 Cinnamaon
mint@mint:~$ sudo grep -i "Using input driver" /var/log/Xorg.0.log
[    20.967] (II) Using input driver 'libinput' for 'Power Button'
[    20.985] (II) Using input driver 'libinput' for 'Video Bus'
[    21.005] (II) Using input driver 'libinput' for 'Power Button'
[    21.022] (II) Using input driver 'libinput' for 'Sleep Button'
[    21.046] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'
[    21.085] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[    21.105] (II) Using input driver 'libinput' for 'SynPS/2 Synaptics TouchPad'
[    21.150] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'

Linux Mint 20 Cinnamon
mint@mint:~$ sudo grep -i "Using input driver" /var/log/Xorg.0.log
[    26.994] (II) Using input driver 'libinput' for 'Power Button'
[    27.027] (II) Using input driver 'libinput' for 'Video Bus'
[    27.059] (II) Using input driver 'libinput' for 'Power Button'
[    27.093] (II) Using input driver 'libinput' for 'Sleep Button'
[    27.128] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'
[    27.174] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[    27.203] (II) Using input driver 'libinput' for 'SynPS/2 Synaptics TouchPad'
[    27.263] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'
[    27.373] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'
[    27.456] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'

Linux Mint 20.1 Cinnamon
mint@mint:~$ grep -i "Using input driver" /var/log/Xorg.0.log
[    26.238] (II) Using input driver 'libinput' for 'Power Button'
[    26.288] (II) Using input driver 'libinput' for 'Video Bus'
[    26.311] (II) Using input driver 'libinput' for 'Power Button'
[    26.345] (II) Using input driver 'libinput' for 'Sleep Button'
[    26.373] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'
[    26.420] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[    26.438] (II) Using input driver 'libinput' for 'SynPS/2 Synaptics TouchPad'
[    26.488] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'
[    26.625] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'


Ubuntu 20.04.1
buntu@ubuntu:~$ sudo grep -i "Using input driver" /var/log/Xorg.0.log
[   224.098] (II) Using input driver 'libinput' for 'Power Button'
[   224.126] (II) Using input driver 'libinput' for 'Video Bus'
[   224.154] (II) Using input driver 'libinput' for 'Power Button'
[   224.175] (II) Using input driver 'libinput' for 'Sleep Button'
[   224.205] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'
[   224.252] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[   224.274] (II) Using input driver 'libinput' for 'SynPS/2 Synaptics TouchPad'
[   224.336] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'
[   243.161] (II) Using input driver 'libinput' for 'Power Button'
[   243.213] (II) Using input driver 'libinput' for 'Video Bus'
[   243.257] (II) Using input driver 'libinput' for 'Sleep Button'
[   243.309] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'
[   243.389] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'
[   243.457] (II) Using input driver 'libinput' for 'Power Button'
[   243.501] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[   243.558] (II) Using input driver 'libinput' for 'SynPS/2 Synaptics TouchPad'
[   253.733] (II) Using input driver 'libinput' for 'Video Bus'
[   253.781] (II) Using input driver 'libinput' for 'Power Button'
[   253.825] (II) Using input driver 'libinput' for 'Sleep Button'
[   253.857] (II) Using input driver 'libinput' for 'Acer WMI hotkeys'
[   253.901] (II) Using input driver 'libinput' for 'Power Button'
[   253.969] (II) Using input driver 'libinput' for 'HD WebCam: HD WebCam'
[   254.017] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[   254.082] (II) Using input driver 'libinput' for 'SynPS/2 Synaptics TouchPad'

**Comment by clefebvre** [comment] 2020-12-31 13:35
Thanks @BertBoer1. I'll close this here since it's not specific to the BETA.

**Closed as completed by clefebvre** 2020-12-31 13:35 UTC
