### ISSUE TITLE
Problem after offline installation of multimedia codecs package....

### ISSUE THREAD

**Issue by lin141** [linuxmint/mint20.1-beta#46] opened 2020-12-22 12:21 UTC
I downloaded beta version 20.1 and I ran this version on my pc from the usb stick, I downloaded the multimedia codecs package using the apt download mint-meta-codecs command in the linux terminal ... then I installed the offline multimedia codecs package and I can't install any more a program from the software manager gives me this error ...The package system is broken  Check if you are using third party repositories.If so disable them,since they are a common source of problems.Furthermore run the following command in a Terminal:apt-get install -f....Details-The following packages have unmet dependencies:

libavcodec-extra: Depends: libavcodec-extra58 (= 7:4.2.4-1ubuntu0.1) but it is not installed
And still in the start menu it shows me that no multimedia codecs have been installed...this error occurs if I install the downloaded offline multimedia codecs package

**Comment by clefebvre** [comment] 2020-12-22 13:34
Duplicate of https://github.com/linuxmint/mint20.1-beta/issues/47

**Closed as completed by clefebvre** 2020-12-22 13:34 UTC
