### ISSUE TITLE
problem installing multimedia codecs...

### ISSUE THREAD

**Issue by lin141** [linuxmint/mint20.1-beta#45] opened 2020-12-22 11:43 UTC
![Peek 2020-12-22 11-04](https://user-images.githubusercontent.com/76395492/102884925-694f3780-444a-11eb-91c5-803aeef952b0.gif)
I downloaded the multimedia codecs archive using the command from the apt download mint-meta-codecs terminal and then I installed the offline codecs

and then it gives me an error software index is broken this is a majore of failure of your software management system...

**Comment by clefebvre** [comment] 2020-12-22 13:34
duplicate of https://github.com/linuxmint/mint20.1-beta/issues/47

**Closed as completed by clefebvre** 2020-12-22 13:34 UTC
