### ISSUE TITLE
Issues...

### ISSUE THREAD

**Issue by lin141** [linuxmint/mint20.1-beta#32] opened 2020-12-20 13:45 UTC
Starting with linux versions 19 to 20.1 beta, it did not solve 2 problems I discovered in these versions first if I want to download the apt download mint-meta-codecs package from the linux terminal does not download the complete package for offline installation, and the second the problem is with the media player trying to change certain mp3 or mp4 files with the mouse that waiting state circle appears which lasts a long time on the screen until it disappears, this is quite annoying on the screen, please the developers to fix these errors, thank you .. .

**Comment by xenopeek** [comment] 2020-12-21 15:24
Duplicate of #31

**Closed as completed by xenopeek** 2020-12-21 15:24 UTC
